apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-boilerplate
  namespace: backend-boilerplate
  labels:
    app: backend-boilerplate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-boilerplate
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'backend-boilerplate'
        vault.hashicorp.com/log-level: 'debug'
        vault.hashicorp.com/agent-inject-status: 'update'
        vault.hashicorp.com/agent-inject-secret-env: 'secret/backend-boilerplate/main'
        vault.hashicorp.com/agent-inject-template-env: |
          {{- with secret "secret/backend-boilerplate/main" -}}
          SQLALCHEMY_DATABASE_URI=mariadb+pymysql://{{ .Data.first_db_user }}:{{ .Data.db_first_pass }}@mariadb-service.backend-boilerplate.svc.cluster.local:3306/{{ .Data.db_name }}
          FIRST_SUPERUSER_EMAIL={{ .Data.first_superuser }}
          FIRST_SUPERUSER_PASSWORD={{ .Data.first_superuser_password }}
          {{- end -}}
      labels:
        app: backend-boilerplate
    spec:
      serviceAccountName: backend-boilerplate
      containers:
      - name: whisper
        image: crpier/whisper
        imagePullPolicy: Always
        env:
          - name: FIRST_SUPERUSER_NAME
            value: admin
          - name: SONGS_PATH
            value: /var/song
        volumeMounts:
          - mountPath: /var/song/
            name: song-volume
      volumes:
        - name: song-volume
          persistentVolumeClaim:
            claimName: song-pv-claim
