apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: song-pv-claim
  namespace: backend-boilerplate
  labels: 
    app: backend-boilerplate
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
